<?php
//数据库配置文件
$config_storage=array(
		"MYSQL"=>array(
						"base"=>array("host"=>"127.0.0.1","user"=>"root","pw"=>"123456","db"=>"game3"),
						"operators"=>array("host"=>"127.0.0.1","user"=>"root","pw"=>"123456","db"=>"server_list"),//如果多个请加上这个
					),
	);
?>